### PR TITLE
NE-1807: Rebase to v2.8.2

### PR DESCRIPTION
**Pull request by alebedev87**
This PR rebases the openshift fork of [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) to [v2.8.2 tag](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/v2.8.2).

Doc with the analysis: [link](https://docs.google.com/document/d/1-i3skgE6JUQwb4Cbq7RFqeyGY1N8Ukv4JkH6rYuffwk/edit).
Rebase procedure which has been followed: [link](https://github.com/openshift/aws-load-balancer-controller/blob/6617f8aed8d3313e70f85354aa0db4b722a22cb4/rebase.md).

Initial list of cherry pick commits which were used as a source before squashes (from bottom up):
```
b84e919ed UPSTREAM <carry>: OCPBUGS-24653: Ensure FIPS compliance for controller image
874c678ff UPSTREAM <carry>: DOWNSTREAN_OWNERS - add NetworkEdge team
d59817b6a UPSTREAM: <carry>: Add ci_operator.yaml config for build root image
bee0499bb UPSTREAM: <carry>: Change golang base image from toolset to ocp builder
b166f9d89 UPSTREAM: <carry>: Switch to UBI for builder image
6617f8aed UPSTREAM: <carry>: Add document with procedure for rebasing
f061bf60c UPSTREAM: <carry>: Change the base image from micro to minimal
93755fc37 UPSTREAM: <carry>: Added Dockerfile used in Openshift builds
654e632a8 UPSTREAM: <carry>: Added downstream owners file
```

Squashed list of check picks with commit messages added as bullet points (from bottom up):
```
5b2c3e40b UPSTREAM: <carry>: Add ci_operator.yaml config for build root image
36afae9a2 UPSTREAM: <carry>: Add document with procedure for rebasing
cfba6a7ef UPSTREAM: <carry>: Added Dockerfile used in Openshift builds
    - Openshift built container images should be based on the Universal Base Image.
    - Change the base image from micro to minimal.
        - The micro image does not have the necessary certificates to make requests to AWS API endpo
    - Change golang base image from toolset to ocp builder.
    - OCPBUGS-24653: Ensure FIPS compliance for controller image
        - Replaced the base image with a non-UBI variant.
        - Added the 'strictfipsruntime' tag to the controller binary.
b1b6f182f UPSTREAM: <carry>: Added downstream owners file
    - Add NetworkEdge team
```

Also, the following carry patches have been added:
- [Vendored dependencies for 2.8.2 rebase](https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/a371a27ea9aa6d2de291f04248785e1969a4e392) (`vendor` dir is used only downstream)
- [Explicitly include mockgen model package in vendor directory](https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/4f6c8f0eca68350176b743048decb8911477658b) (`mockgen` utility has been added upstream, it needs this package as a dependency)
- [CI - update golang to 1.22 for 2.8.2 rebase](https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/03a729ddb78a94a0dac125faf66be61c8c4cefc6)

Test PR: https://github.com/openshift/aws-load-balancer-operator/pull/136.

### CODE REVIEW

**Comment by candita** [comment]
Fixes #22

**Comment by gcs278** [comment]
@alebedev87 Any reason not to squash product build related commits?

In CoreDNS, we have a commit https://github.com/openshift/coredns/commit/90d7eed7b801286151ccd624be9989f2008c9d8d that just handles "Product Build Config" such as the Dockerfiles and ci_operator.yaml. That's just how I've done it, but I would recommend considering at least squashing these commits that touch the `Dockerfile.openshift`:
- https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/deaf8dcb9aa628dc87db8ec35f63ce0f406559b3
- https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/6be7dc6f5957aae25046a7014640f86a5645431f
- https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/67b70395689ffb578bfd5a2fb4395c8bae8fa9c5
- https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/f7e46a2ada8ed3867d6975062272d5b709cf357c

**Comment by gcs278** [comment]
@alebedev87 I reproduced your rebase and was able to match 1:1, so that's good, the rebase mechanics seem reasonable. Generally LGTM.

Couple of thoughts, all nit picks, some of my opinion that you should feel free to push back on, but nothing serious:
- Looks like you squashed 5a768db91 into 47b022641c5bd9e8f1e600752b4cadb6bce6e39b. That's fine, but we could also just drop that commit since Thejas has moved on.
- I think the [Merge branch 'main' into rebase](https://github.com/openshift/aws-load-balancer-controller/pull/23/commits/d89b29c2c0de047c2a87b95ef6b9e6f9cd603c90) commit message should be something like `merge kubernetes/aws-load-balancer-controller v2.8.3` to be more descriptive, like how we do it in CoreDNS: https://github.com/openshift/coredns/commit/22d5f9e222defed49ffe0632ec224cf1b4f6c8a8
- I think it'd be helpful to provide the `git cherry-pick...` commands and output, including merge resolutions, and skipped empty commits. The rebase instructions linked are obvious up until you have to actually do the cherry-pick.
  - I see your list of commits, but does that directly translate to a `git cherry-pick` command? Or is that simply the product of the cherry-pick? 
- You switched the vendored commit from `<drop>` to `<carry>`. I'm not sure it matters. We `<carry>` the vendor commit in CoreDNS, but you have to regenerate it anyways. `<drop>` may be more obvious that it needs to be regenerated, so I don't know.
  - No real issue: I just want to make sure it was intentional and you don't prefer `<drop>` to `<carry>`
- What about the comment about the readiness probe in https://docs.google.com/document/d/1-i3skgE6JUQwb4Cbq7RFqeyGY1N8Ukv4JkH6rYuffwk/edit?
  > [add webhook readiness check ](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3375). Readiness probe for webhooks is added to the controller. There are multiple webhooks including the new service mutator. Note: controller’s deployment manifest has to be updated with a readiness probe similar to the one from this PR!
  - Is that something done in the `aws-load-balancer-operator`? Should we have a PR ready-to-go?

**Comment by alebedev87** [comment]
- Squashed `Dockerfile.openshift` and `OWNERS` commits
- Updated the merge to commit to `Merge kubernetes-sigs/aws-load-balancer-controller v2.8.2`

The final cherry picks (with squashed commit messages as bullet points):
```
5b2c3e40b UPSTREAM: <carry>: Add ci_operator.yaml config for build root image
36afae9a2 UPSTREAM: <carry>: Add document with procedure for rebasing
cfba6a7ef UPSTREAM: <carry>: Added Dockerfile used in Openshift builds
    - Openshift built container images should be based on the Universal Base Image.
    - Change the base image from micro to minimal.
        - The micro image does not have the necessary certificates to make requests to AWS API endpo
    - Change golang base image from toolset to ocp builder.
    - OCPBUGS-24653: Ensure FIPS compliance for controller image
        - Replaced the base image with a non-UBI variant.
        - Added the 'strictfipsruntime' tag to the controller binary.
b1b6f182f UPSTREAM: <carry>: Added downstream owners file
    - Add NetworkEdge team
```

**Comment by alebedev87** [comment]
> -  I think it'd be helpful to provide the git cherry-pick... commands and output, including merge resolutions, and skipped empty commits. The rebase instructions linked are obvious up until you have to actually do the cherry-pick.
>     - I see your list of commits, but does that directly translate to a git cherry-pick command? Or is that simply the product of the cherry-pick?

The initial list from the PR description was just a direct order of commits I cherry picked (I don't remember squashing but it's a little fuzzy now). [What I just did](https://github.com/openshift/aws-load-balancer-controller/pull/23#issuecomment-2422411204) includes the commit messages of the squashed commits so it should be easy enough to reproduce the exact sequence.

> You switched the vendored commit from <drop> to <carry>. I'm not sure it matters. We <carry> the vendor commit in CoreDNS, but you have to regenerate it anyways. <drop> may be more obvious that it needs to be regenerated, so I don't know.

I think neither is accurate in this case, we want to carry the vendor directory but with different contents. Right, it used to be `<drop>` let's continue this way.

> What about the comment about the readiness probe ? Is that something done in the aws-load-balancer-operator? Should we have a PR ready-to-go?

Yes, we'll do it in the operator. We already had wehbook servers this will be another one, nothing will break without readiness probe. So we can do it later in the operator repo.

**Comment by alebedev87** [comment]
`build10` cluster is experiencing problems: [test platform announce](https://redhat-internal.slack.com/archives/CFUGK0K9R/p1729259733386509).

**Comment by gcs278** [comment]
Thanks for the updates. Everything looks good to me. I haven't reviewed every single change with 2.8.2, but since we reviewed the important ones in the meeting, I feel pretty confident. I do recognize that this rebase is inherently risky, given the amount of changes coming in, but it's something we need to do regardless.

/approve
/lgtm

@alebedev87 do you want to wait for @Miciah's review? Remove as you wish.
/hold

**Comment by alebedev87** [comment]
/unhold

https://redhat-internal.slack.com/archives/CBWMXQJKD/p1733303654250399

**Comment by alebedev87** [comment]
/label px-approved
/label docs-approved

The epic has a dedicated docs task.

**Comment by ShudiLi** [comment]
/label qe-approved
I will test it with another alb-operator PR, thanks.

**Pull request merged**
