### PR TITLE
CFE-617: Rebase v2.4.4

### PR DESCRIPTION
**Pull request by thejasn**
### Description
Rebase controller to v2.4.4. Steps followed.

- `git checkout -b rebase-2.4.4 v2.4.4`
- `git merge -s ours openshift/main`
- Compared diff before and after merge using `git diff openshift/main v2.4.4` [Diff is the same]
---
Note:
- upstream set to https://github.com/kubernetes-sigs/aws-load-balancer-controller
- openshift set to https://github.com/openshift/aws-load-balancer-controller
- Rebase PR breakdown: https://docs.google.com/document/d/1GONQ3rEkGzQx6SLvkb928eLdbQO4P-wI5qpxLk_oC88

### CODE REVIEW

**Comment by gcs278** [comment]
> Should we disable the IP mode since this feature gate is available upstream?

I'm a bit confused by this, maybe I'm misunderstanding. We pull an upstream commit to enable this feature-gate (which defaults to `true`) and now the rebase pulls in that feature gate (which defaults to `true`). Why would we need to do anything differently other than just dropping the carry now that it's in our rebase?

**Comment by gcs278** [comment]
> Should we disable the reconciliation of the services since they are not needed for the moment?

Does it do any harm to leave it enabled?

**Comment by thejasn** [comment]
> > Should we disable the IP mode since this feature gate is available upstream?
> 
> I'm a bit confused by this, maybe I'm misunderstanding. We pull an upstream commit to enable this feature-gate (which defaults to `true`) and now the rebase pulls in that feature gate (which defaults to `true`). Why would we need to do anything differently other than just dropping the carry now that it's in our rebase?

So `target-type=ip` is not supported on Openshift since it requires AWS VPC CNI and prior to the upstream patch which added `EnableIPTargetType` feature gate there was no error on the controller when `target-type` was set to `ip` on Openshift. So the feature gate allows us to disable this `target-type` which in turns gives an explicit error `Unsupported target-type=ip`. 
The follow up PR on the operator is https://github.com/openshift/aws-load-balancer-operator/pull/80

**Comment by thejasn** [comment]
> > Should we disable the reconciliation of the services since they are not needed for the moment?
> 
> Does it do any harm to leave it enabled?

No, we decided we will allow reconciliation of Services as is and just document that the operator will support `Service` type resources as well by creating NLBs for them. Docs [PR](https://github.com/openshift/openshift-docs/pull/52309) for the same.

**Comment by gcs278** [comment]
Looks good to me after reading through all of the changes, but since it's already approved, and a LGTM would merge it, @Miciah do you have any concerns or want a chance to review before I LGTM it?

**Comment by gcs278** [comment]
Thanks I forgot about lgtm and hold.
/lgtm

**Comment by thejasn** [comment]
/label px-approved

As per Chris Fields: the docs are enough for this release of AWS Load Balancer Operator.

**Pull request merged**
